# Generated by Django 3.1.3 on 2021-03-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_fat', models.FloatField()),
                ('per_sugar_raw', models.FloatField()),
                ('per_sugar_cooked', models.FloatField()),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.items')),
            ],
        ),
    ]
